### ISSUE TITLE
メモ

### ISSUE THREAD

**Issue by takapi327** [takapi327/learners-dictionary#12]
# GitHub Actions 環境構築
## 手順
- [x] GitHubレポジトリへSecret Key設定
- [x] GitHub Actions Workflow Yamlファイルの設定
## Step1. GitHubレポジトリへSecret Key設定
このブランチが、AWSに対してアクセスできるようにアクセスキーの設定を行います。
まず、下記画像のようにブランチの「Settings」タブを選択します。
画面が切り替わったら「Secrets」を選択します。
「new secret」を選択してキーの設定を行います。
<img width="1330" alt="スクリーンショット 2020-10-17 17 07 23" src="https://user-images.githubusercontent.com/57429437/96331807-3af45b00-109b-11eb-9d5a-9680935d275a.png">
下記画像のように、nameを「AWS_ACCESS_KEY_ID」にして、IAMで作成したユーザーのキーを貼り付けます。
貼り付けが終われば、「Add sercret」でキーの生成を行います。
「AWS_SECRET_ACCESS_KEY」も同様に設定を行います。
<img width="750" alt="スクリーンショット 2020-10-17 17 08 00" src="https://user-images.githubusercontent.com/57429437/96331819-51021b80-109b-11eb-89cd-0edbae85fcca.png">
作成が終わり、下記のように表示されていれば成功です。
<img width="746" alt="スクリーンショット 2020-10-17 17 10 00" src="https://user-images.githubusercontent.com/57429437/96331852-9888a780-109b-11eb-8764-2782f2e03006.png">
次に、Github Actionsを動かすコードを書いていきます。
ブランチの「Actions」タブを選択します。
一番上にこのブランチで使用している言語用のActionsが表示されていると思うので、その「Set up this workflow」を選択します。(今回はScalaを使用していたので、Scalaで実装を行います)
選択すると画面が切り替わり、デフォルトの設定が表示されているので、表示されているコードを今回行いたい設定ように修正していきます。
<img width="874" alt="スクリーンショット 2020-10-17 17 12 06" src="https://user-images.githubusercontent.com/57429437/96331884-e3a2ba80-109b-11eb-81dc-089c5227308a.png">

### AWSへ認証設定
まずAWSへアクセスできるように認証設定を行っていきます。
記述は、下記のAWSの書き方通りで問題ないです。
https://github.com/aws-actions/configure-aws-credentials
先ほどGithubで設定した、キーを記載しています。
```yml
- name: Configure AWS Credentials
  uses: aws-actions/configure-aws-credentials@v1
    with:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws-region: ap-northeast-1
```

### ECR設定
次にECRに対して、docker imageをpushする設定を行います。
書き方は、下記を参考にbuildの処理を変更しています。
https://github.com/aws-actions/amazon-ecr-login

今回docker imageのbuildをsbtを使用して実装を行いましたので、AWS通りに実装を行ってもうまく動作しません。
前回docker imageを作成した手順(コマンド)をそのままGithub Actionsでも行えばうまく動作しますので、記述を変更しています。
```yml
- name: Login to Amazon ECR
  id: login-ecr
  uses: aws-actions/amazon-ecr-login@v1
      
- name: Build, tag, and push image to Amazon ECR
  env:
    ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
    ECR_REPOSITORY: project/repository_for_cap
    IMAGE_TAG: latest
    run: |
      sbt docker:publishLocal
      docker tag core-archive-project:1.0-SNAPSHOT $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
      docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
```

### ECSログイン設定
最後にECSの設定を行い、作成したService起動する処理を行います。
ECSの設定に関しても、下記AWSの設定を使用し、自身の設定に変更すれば問題なく動作します。
https://github.com/aws-actions/amazon-ecs-render-task-definition

```yml
- name: Render Amazon ECS task definition
  id: render-web-container
    uses: aws-actions/amazon-ecs-render-task-definition@v1
    with:
      task-definition: aws/task-definition.json
      container-name: container-for-cap
      image: {アカウント}.dkr.ecr.ap-northeast-1.amazonaws.com/project/repository_for_cap:latest
        
- name: Deploy to Amazon ECS service
  uses: aws-actions/amazon-ecs-deploy-task-definition@v1
  with:
    task-definition: ${{ steps.render-web-container.outputs.task-definition }}
    service: container-for-cap-service
    cluster: cluster-for-cap
```

最終的な設定は下記のようになります。
実際にmasterブランチに変更を加えて、Github Actionsが動作するか確認してみます。
```yml
name: Deploy App

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      
    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: project/repository_for_cap
        IMAGE_TAG: latest
      run: |
        sbt docker:publishLocal
        docker tag {Docker image名}:1.0-SNAPSHOT $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    - name: Render Amazon ECS task definition
      id: render-web-container
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: aws/task-definition.json
        container-name: container-for-cap
        image: {アカウント}.dkr.ecr.ap-northeast-1.amazonaws.com/project/repository_for_cap:latest
        
    - name: Deploy to Amazon ECS service
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.render-web-container.outputs.task-definition }}
        service: container-for-cap-service
        cluster: cluster-for-cap
```

## Welcome to Pla! -> Hello World!
下記のように、文言を変更してmasterブランチにマージしてみます。
```html
@main("Hello World!") {
  <h1>Hello World!</h1>
}
```

## 参考文献
[AWS for GitHub Actions](https://github.com/aws-actions)
[GitHub Actions のコンテキストおよび式の構文](https://docs.github.com/ja/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions)
[sbt-native-packager](https://github.com/sbt/sbt-native-packager)
[GitHub ActionsからAmazon ECSにアプリをデプロイ](https://qiita.com/momotaro98/items/a0791969172ac94cfe47)
[[AWS] Amazon ECS(EC2タイプ)のちょっと長めのチュートリアル(第1回)](https://qiita.com/VA_nakatsu/items/c8a4b24b8cffd0e9047b)
[Tag GitHub ActionでDockerコンテナをビルドしてAmazon ECRに保存する](https://dev.classmethod.jp/articles/github-action-ecr-push/)
[初心者がAmazon ECSのチュートリアルを試した](https://qiita.com/JJ33/items/e3a32d17bb7e8f7d53a5)
